version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: some_password
      POSTGRES_USER: unleash_user
      POSTGRES_DB: unleash
    networks:
      - unleash_network

  unleash:
    image: unleashorg/unleash-server
    container_name: unleash
    ports:
      - "4242:4242"
    environment:
      DATABASE_HOST: postgres
      DATABASE_NAME: unleash
      DATABASE_USERNAME: unleash_user
      DATABASE_PASSWORD: some_password
      DATABASE_SSL: "false"
    depends_on:
      - postgres
    networks:
      - unleash_network

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 150M
    networks:
      - unleash_network

networks:
  unleash_network:
    driver: bridge